export { default as Login } from './Login'
export { default as Registration } from './Registration'
export { default as Main } from './Main'
export { default as Albums } from './Albums'
export { default as AlbumPage } from './Album'
export { default as Profile } from './Profile'
